# Generated by Django 4.2.7 on 2023-12-08 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phonenumber', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format. Example: +989123456789 or 09123456789', regex='^(?:\\+98|0)?9[0-9]{2}(?:[0-9](?:[ -]?[0-9]{3}){2}|[0-9]{8})$')], verbose_name='Phone number')),
                ('email', models.EmailField(max_length=100, verbose_name='email address')),
                ('username', models.CharField(blank=True, help_text='Create the default username using the format firstname_lastname@cofe', max_length=40, null=True)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('how_know_us', models.CharField(choices=[('Ch_Tel', 'Chanel Telegram'), ('Ins', 'Instagram'), ('Web', 'Web Site'), ('Fr', 'Friends'), ('Other', 'Other items')], default='None')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
