<<<<<<< HEAD
# Generated by Django 5.0 on 2023-12-10 08:39

import account.models
import datetime
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phonenumber', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format. Example: +989123456789 or 09123456789', regex='^(?:\\+98|0)?9[0-9]{2}(?:[0-9](?:[ -]?[0-9]{3}){2}|[0-9]{8})$')], verbose_name='Phone number')),
                ('email', models.EmailField(max_length=100, verbose_name='email address')),
                ('username', models.CharField(blank=True, help_text='Create the default username using the format firstname_lastname@cofe', max_length=40, null=True)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('how_know_us', models.CharField(choices=[('Ch_Tel', 'Chanel Telegram'), ('Ins', 'Instagram'), ('Web', 'Web Site'), ('Fr', 'Friends'), ('Other', 'Other items')], default='None')),
                ('is_customer', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nationalcode', models.CharField(max_length=20, unique=True, validators=[account.models.ValidatorMixin.nationalcode_validator], verbose_name='National Code')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(1380, 1, 1), null=True, verbose_name='birth day')),
                ('experience', models.IntegerField(default=None, null=True)),
                ('rezome', models.FileField(blank=True, null=True, upload_to='files/')),
                ('profile_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='images/')),
                ('guarantee', models.CharField(choices=[('Ch', 'Check'), ('Prn', 'Promissory note'), ('rep', 'Representative')], default='None')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.customuser', models.Model, account.models.ValidatorMixin),
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
||||||| 9562907
=======
# Generated by Django 4.2.7 on 2023-12-06 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phonenumber', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format. Example: +989123456789 or 09123456789', regex='^(?:\\+98|0)?9[0-9]{2}(?:[0-9](?:[ -]?[0-9]{3}){2}|[0-9]{8})$')], verbose_name='Phone number')),
                ('email', models.EmailField(max_length=100, verbose_name='email address')),
                ('username', models.CharField(blank=True, help_text='Create the default username using the format firstname_lastname@cofe', max_length=40, null=True)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('how_know_us', models.CharField(choices=[('Ch_Tel', 'Chanel Telegram'), ('Ins', 'Instagram'), ('Web', 'Web Site'), ('Fr', 'Friends'), ('Other', 'Other items')], default='None', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
>>>>>>> 338cad193e2076042d495a69c9a311ef9c4cb123
