# Generated by Django 5.0 on 2023-12-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='admin@cofe', help_text='Create the default username using the format firstname_lastname@cofe', max_length=40, null=True),
        ),
    ]
