# Generated by Django 5.0 on 2023-12-10 15:56

import account.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='nationalcode',
            field=models.CharField(max_length=50, unique=True, validators=[account.models.ValidatorMixin.nationalcode_validator], verbose_name='National Code'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='rezome',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/'),
        ),
    ]
