# Generated by Django 5.0 on 2023-12-06 13:15

import account.models
import datetime
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalcode', models.CharField(max_length=20, unique=True, validators=[account.models.ValidatorMixin.nationalcode_validator], verbose_name='National Code')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(1380, 1, 1), null=True, verbose_name='birth day')),
                ('experience', models.IntegerField(default=None, null=True)),
                ('rezome', models.FileField(blank=True, null=True, upload_to='files/')),
                ('profile_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='images/')),
                ('guarantee', models.CharField(choices=[('Ch', 'Check'), ('Prn', 'Promissory note'), ('rep', 'Representative')], default='None')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, account.models.ValidatorMixin),
        ),
    ]
