<<<<<<< HEAD
# Generated by Django 5.0 on 2023-12-10 08:39
||||||| 9562907
# Generated by Django 4.2.7 on 2023-12-05 19:28
=======
# Generated by Django 4.2.7 on 2023-12-06 15:24
>>>>>>> 338cad193e2076042d495a69c9a311ef9c4cb123

<<<<<<< HEAD
||||||| 9562907
from django.conf import settings
from django.db import migrations, models
=======
from django.db import migrations, models
>>>>>>> 338cad193e2076042d495a69c9a311ef9c4cb123
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
||||||| 9562907
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('id_Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.items')),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
>>>>>>> 338cad193e2076042d495a69c9a311ef9c4cb123
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
||||||| 9562907
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.items')),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
>>>>>>> 338cad193e2076042d495a69c9a311ef9c4cb123
            ],
        ),
    ]
