# Generated by Django 4.2.7 on 2023-12-06 15:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('serving_time', models.CharField(choices=[('M', 'morning'), ('N', 'noon'), ('E', 'evening'), ('N', 'night')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=255)),
                ('status', models.BooleanField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2)),
                ('number_items', models.PositiveIntegerField(blank=True, default=1)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.categorymenu')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='cart', max_length=10)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('number_items', models.PositiveIntegerField(blank=True, default=1)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('delivery_time', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('items', models.ManyToManyField(related_name='item_order', to='cafe.items')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_time'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='like',
            field=models.ManyToManyField(related_name='liked_item', through='cafe.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.order')),
            ],
            options={
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['-time'], name='cafe_receip_time_948097_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-order_time'], name='cafe_order_order_t_27399b_idx'),
        ),
    ]
