# Generated by Django 4.2.7 on 2023-12-05 19:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('serving_time', models.CharField(blank=True, choices=[('M', 'morning'), ('N', 'noon'), ('E', 'evening'), ('N', 'night')], max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=255)),
                ('status', models.BooleanField()),
                ('likes', models.CharField(blank=True, choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'good'), ('4', 'very good'), ('5', 'extra good')], max_length=10, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.categorymeno')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('delivery_time', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='item_order', through='cafe.ItemOrder', to='cafe.items')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_time'],
            },
        ),
        migrations.AddField(
            model_name='itemorder',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.items'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cafe.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-order_time'], name='cafe_order_order_t_27399b_idx'),
        ),
    ]
