# Generated by Django 4.2.7 on 2023-12-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorymeno',
            name='serving_time',
            field=models.CharField(choices=[('M', 'morning'), ('N', 'noon'), ('E', 'evening'), ('N', 'night')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='likes',
            field=models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'good'), ('4', 'very good'), ('5', 'extra good')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
