# Generated by Django 5.0 on 2023-12-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_items',
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='cart', max_length=10),
        ),
        migrations.AlterField(
            model_name='items',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='items',
            name='number_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='item_order', to='cafe.items'),
        ),
    ]
