# Generated by Django 4.2.7 on 2023-12-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
