# Generated by Django 4.2.7 on 2023-12-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_order_number_items_alter_items_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='cart', max_length=10),
        ),
    ]
